apiVersion: apps/v1
kind: Deployment
metadata:
  name: foursix-payment-deployment
  labels:
    app: foursix-payment-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: foursix-payment-deployment
  template:
    metadata:
      labels:
        app: foursix-payment-deployment
    spec:
      containers:
      - name: c-foursix-payment-deployment
        image: ivangomesneto/four-six-payment-api:latest
        ports:
        - containerPort: 80
