apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-payment-volume
  namespace: mssql
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Mi
  persistentVolumeReclaimPolicy: Retain
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/opt/mssql/data"