apiVersion: v1
kind: Service
metadata:
  labels:
    app: api-svc-payment-foursix
  name: api-svc-payment-foursix
spec:
  selector:
    app: foursix-payment-deployment
  ports:
  - port: 30040
    protocol: TCP
    targetPort: 80
  type: LoadBalancer
